### ISSUE TITLE
Any plans on open sourcing?

### ISSUE THREAD

**Issue by jiaxiaosong1002** [woxihuanjiangguo/BEVNeXt#1]
Dear authors,
@woxihuanjiangguo 
I am wondering about your plan for open sourcing, as indicated in your arXiv paper.

Thanks!

**Comment by woxihuanjiangguo** [comment]
Hi @jiaxiaosong1002 , sorry for the delayed response. We are in the process of cleaning codes and plan to release them by the end of this month.
