### ISSUE TITLE
mmcv/mmdetection3d versions

### ISSUE THREAD

**Issue by RanBenIzhak** [woxihuanjiangguo/BEVNeXt#3]
Hi,
Thanks for the great work!

Due to the incompatibility between different versions of mmcv/mmdetection3d, can you please provide the exact versions of the packages installed?

a complete requirements.txt file / docker would be of much help.

thanks!

**Comment by woxihuanjiangguo** [comment]
Hello, we updated the [document](https://github.com/woxihuanjiangguo/BEVNeXt/blob/master/docs/en/getting_started.md) for installation. Please let me know if these versions work for you.
