### ISSUE TITLE
Meaning of ego-motion transformation in BEVNeXt paper

### ISSUE THREAD

**Issue by tjqansthd** [woxihuanjiangguo/BEVNeXt#4]
Hi, thanks for your great work!

I have a question about the operation of ego-motion transformation. In the paper, it is mentioned as "The increased receptive field, in turn, allow us to skip ego-motion transformation across historical BEVs, which avoids motion misalignment issues [20] in advance techniques". This expression seems to be that the BEVNeXT model skips the entire process of ego motion compensation between temporary frames. However, in the code, it is only expressed as ```align_after_view_transformation=False```, which means that the ego-motion transformation process is not performed after the view transformation, but is included in the view transformation process (the LUT is created through "sensor_(t-1) to ego_(t)" matrix when converting past frame views.)

Generally, performance is better when the ```align_after_view_transformation``` option is set to False than when it is set to True.
(https://github.com/HuangJunJie2017/BEVDet/blob/26144be7c11c2972a8930d6ddd6471b8ea900d13/configs/bevdet/bevdet-r50-4dlongterm-cbgs.py)

If my opinion doesn't get it wrong, I think the performance variance with or without Ego-motion Trans. in Table 6 of the paper was not due to whether or not ego-motion transformation was applied, but whether the ego-motion transformation was separated after the view transformation process, or included within the view transformation. Is the intention on the paper different from what I think?

**Comment by woxihuanjiangguo** [comment]
Thanks for your precious comments. Your understanding is basically correct. The ego-motion compensation in the paper was intended as the post-alignment (which happens after view transformation as you mentioned). We will quickly clarify this to avoid ambiguity.
